### ISSUE TITLE
Missing labelNoun in HediffDefs

### ISSUE THREAD

**Issue by fiziologus** [RimWorld-zh/RimWorld-English#1]
Files:
Defs/Drugs/Alcohol_Beer.xml
Defs/Drugs/GoJuice.xml
Defs/Drugs/Psychite_Flake.xml
Defs/Drugs/Psychite_Pekoe.xml
Defs/Drugs/Psychite_Yayo.xml
Defs/Drugs/Smokeleaf.xml
Defs/Drugs/WakeUp.xml
Defs/HediffDefs/Hediffs_Global_Execution.xml
Defs/HediffDefs/Hediffs_Global_Misc.xml
Defs/HediffDefs/Hediffs_Local_AddedParts.xml
Defs/HediffDefs/Hediffs_Local_Chronic.xml
Defs/HediffDefs/Hediffs_Local_Implants.xml
Defs/HediffDefs/Hediffs_Local_Infections.xml
Defs/HediffDefs/Hediffs_Local_Injuries.xml
Defs/HediffDefs/Hediffs_Local_Misc.xml

This use in RulePackDefs/RulePacks_Transitions.xml.

**Comment by duduluu** [comment]
Thanks! I'll fix them tonight.

**Comment by duduluu** [comment]
Fixed. Thanks!
